# Generated by Django 5.2.4 on 2025-07-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='favorite_routs',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='journeys.route'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
